//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using DevExpress.ExpressApp.DC;
using DevExpress.Persistent.Base;
using DevExpress.Persistent.BaseImpl;
using DevExpress.Xpo;
namespace XAFSkelbimaiPrograma.Module.BusinessObjects.ORMDataModelCode.Objects
{
  [DefaultClassOptions]
  public partial class SKRule : DevExpress.Persistent.BaseImpl.BaseObject
  {
    private XAFSkelbimaiPrograma.Module.BusinessObjects.ORMDataModelCode.Classificators.SKRuleType _ruleType;
    private System.DateTime _lastRunTime;
    private System.DateTime _runTime;
    private System.String _ruleNameSpace;
    private System.String _name;
    public SKRule(DevExpress.Xpo.Session session)
      : base(session)
    {
    }
    public System.String Name
    {
      get
      {
        return _name;
      }
      set
      {
        SetPropertyValue("Name", ref _name, value);
      }
    }
    [DevExpress.Xpo.SizeAttribute(500)]
    public System.String RuleNameSpace
    {
      get
      {
        return _ruleNameSpace;
      }
      set
      {
        SetPropertyValue("RuleNameSpace", ref _ruleNameSpace, value);
      }
    }
    public System.DateTime RunTime
    {
      get
      {
        return _runTime;
      }
      set
      {
        SetPropertyValue("RunTime", ref _runTime, value);
      }
    }
    public System.DateTime LastRunTime
    {
      get
      {
        return _lastRunTime;
      }
      set
      {
        SetPropertyValue("LastRunTime", ref _lastRunTime, value);
      }
    }
    public XAFSkelbimaiPrograma.Module.BusinessObjects.ORMDataModelCode.Classificators.SKRuleType RuleType
    {
      get
      {
        return _ruleType;
      }
      set
      {
        SetPropertyValue("RuleType", ref _ruleType, value);
      }
    }
  }
}
