//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using DevExpress.ExpressApp.DC;
using DevExpress.Persistent.Base;
using DevExpress.Persistent.BaseImpl;
using DevExpress.Xpo;
namespace XAFSkelbimaiPrograma.Module.BusinessObjects.ORMDataModelCode.Objects
{
  [DefaultClassOptions]
  public partial class SKUserLicense : DevExpress.Persistent.BaseImpl.BaseObject
  {
    private XAFSkelbimaiPrograma.Module.BusinessObjects.ORMDataModelCode.Classificators.SKLicenseType _licenseType;
    private XAFSkelbimaiPrograma.Module.SecurityModule.DLCEmployee _sKUser;
    private System.Decimal _paid;
    private System.Boolean _blocked;
    private System.DateTime _dateTo;
    private System.DateTime _dateFrom;
    public SKUserLicense(DevExpress.Xpo.Session session)
      : base(session)
    {
    }
    public System.DateTime DateFrom
    {
      get
      {
        return _dateFrom;
      }
      set
      {
        SetPropertyValue("DateFrom", ref _dateFrom, value);
      }
    }
    public System.DateTime DateTo
    {
      get
      {
        return _dateTo;
      }
      set
      {
        SetPropertyValue("DateTo", ref _dateTo, value);
      }
    }
    public System.Boolean Blocked
    {
      get
      {
        return _blocked;
      }
      set
      {
        SetPropertyValue("Blocked", ref _blocked, value);
      }
    }
    public System.Decimal Paid
    {
      get
      {
        return _paid;
      }
      set
      {
        SetPropertyValue("Paid", ref _paid, value);
      }
    }
    [Association("Employee-License")]
    public XAFSkelbimaiPrograma.Module.SecurityModule.DLCEmployee SKUser
    {
      get
      {
        return _sKUser;
      }
      set
      {
        SetPropertyValue("SKUser", ref _sKUser, value);
      }
    }
    public XAFSkelbimaiPrograma.Module.BusinessObjects.ORMDataModelCode.Classificators.SKLicenseType LicenseType
    {
      get
      {
        return _licenseType;
      }
      set
      {
        SetPropertyValue("LicenseType", ref _licenseType, value);
      }
    }
  }
}
