//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using DevExpress.ExpressApp.DC;
using DevExpress.Persistent.Base;
using DevExpress.Persistent.BaseImpl;
using DevExpress.Xpo;
namespace XAFSkelbimaiPrograma.Module.BusinessObjects.ORMDataModelCode.Classificators
{
  [DefaultClassOptions]
  public partial class SKLicenseType : DevExpress.Persistent.BaseImpl.BaseObject
  {
    private System.Int32 _urlLinkCount;
    private System.String _name;
    public SKLicenseType(DevExpress.Xpo.Session session)
      : base(session)
    {
    }
    public System.String Name
    {
      get
      {
        return _name;
      }
      set
      {
        SetPropertyValue("Name", ref _name, value);
      }
    }
    public System.Int32 UrlLinkCount
    {
      get
      {
        return _urlLinkCount;
      }
      set
      {
        SetPropertyValue("UrlLinkCount", ref _urlLinkCount, value);
      }
    }
  }
}
