//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using DevExpress.ExpressApp.DC;
using DevExpress.Persistent.Base;
using DevExpress.Persistent.BaseImpl;
using DevExpress.Xpo;
namespace XAFSkelbimaiPrograma.Module.BusinessObjects.ORMDataModelCode.Classificators
{
  [DefaultClassOptions]
  public partial class SKLicenseType : DevExpress.Persistent.BaseImpl.BaseObject
  {
    private System.Boolean _photo;
    private System.Decimal _priceMonth12;
    private System.Decimal _priceMonth6;
    private System.Decimal _priceMonth1;
    private System.Boolean _email;
    private System.Int32 _urlLinkCount;
    private System.String _name;
    public SKLicenseType(DevExpress.Xpo.Session session)
      : base(session)
    {
    }
    public System.String Name
    {
      get
      {
        return _name;
      }
      set
      {
        SetPropertyValue("Name", ref _name, value);
      }
    }
    public System.Int32 UrlLinkCount
    {
      get
      {
        return _urlLinkCount;
      }
      set
      {
        SetPropertyValue("UrlLinkCount", ref _urlLinkCount, value);
      }
    }
    public System.Boolean Email
    {
      get
      {
        return _email;
      }
      set
      {
        SetPropertyValue("Email", ref _email, value);
      }
    }
    public System.Decimal PriceMonth1
    {
      get
      {
        return _priceMonth1;
      }
      set
      {
        SetPropertyValue("PriceMonth1", ref _priceMonth1, value);
      }
    }
    public System.Decimal PriceMonth6
    {
      get
      {
        return _priceMonth6;
      }
      set
      {
        SetPropertyValue("PriceMonth6", ref _priceMonth6, value);
      }
    }
    public System.Decimal PriceMonth12
    {
      get
      {
        return _priceMonth12;
      }
      set
      {
        SetPropertyValue("PriceMonth12", ref _priceMonth12, value);
      }
    }
    public System.Boolean Photo
    {
      get
      {
        return _photo;
      }
      set
      {
        SetPropertyValue("Photo", ref _photo, value);
      }
    }
  }
}
